# Generated by Django 4.2.20 on 2025-05-27 16:42

import accounts.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nickname', models.CharField(max_length=20, unique=True)),
                ('gender', models.CharField(choices=[('M', '남성'), ('F', '여성')], max_length=1)),
                ('salary', models.CharField(choices=[('under_30m', '3천만원 미만'), ('30m_50m', '3천만원~5천만원'), ('50m_100m', '5천만원~1억원'), ('over_100m', '1억원 이상')], max_length=20)),
                ('wealth', models.CharField(choices=[('under_10m', '1천만원 미만'), ('10m_30m', '1천~3천만원'), ('30m_50m', '3천~5천만원'), ('50m_100m', '5천~1억원'), ('over_100m', '1억원 이상')], max_length=20)),
                ('tendency', models.CharField(choices=[('safe', '안정형'), ('neutral', '중립형'), ('aggressive', '공격형')], max_length=20)),
                ('deposit_amount', models.CharField(choices=[('under_100k', '10만원 미만'), ('100k_500k', '10~50만원'), ('500k_1m', '50~100만원'), ('over_1m', '100만원 이상')], max_length=20)),
                ('deposit_period', models.CharField(choices=[('under_6m', '6개월 미만'), ('6m_12m', '6~12개월'), ('1y_2y', '1~2년'), ('over_2y', '2년 이상')], max_length=20)),
                ('has_completed_profile', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', accounts.models.CustomUserManager()),
            ],
        ),
    ]
