# Generated by Django 4.2.20 on 2025-05-26 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='has_completed_profile',
            field=models.BooleanField(default=False),
        ),
    ]
