# Generated by Django 4.2.20 on 2025-05-27 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoldPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('close_last', models.DecimalField(decimal_places=3, max_digits=10)),
                ('volume', models.DecimalField(decimal_places=3, max_digits=15)),
                ('open_price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('high', models.DecimalField(decimal_places=3, max_digits=10)),
                ('low', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
            options={
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='SilverPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('close_last', models.DecimalField(decimal_places=3, max_digits=10)),
                ('volume', models.DecimalField(decimal_places=3, max_digits=15)),
                ('open_price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('high', models.DecimalField(decimal_places=3, max_digits=10)),
                ('low', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
