# Generated by Django 4.2.20 on 2025-05-26 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goldprice',
            name='date',
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name='silverprice',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
