# Generated by Django 4.2.20 on 2025-05-27 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'deposit_interest',
            },
        ),
        migrations.CreateModel(
            name='DepositJoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'deposit_join',
            },
        ),
        migrations.CreateModel(
            name='SavingInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'saving_interest',
            },
        ),
        migrations.CreateModel(
            name='SavingJoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'saving_join',
            },
        ),
        migrations.CreateModel(
            name='SavingProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dcls_month', models.TextField()),
                ('fin_co_no', models.TextField()),
                ('kor_co_nm', models.TextField()),
                ('fin_prdt_cd', models.TextField()),
                ('fin_prdt_nm', models.TextField()),
                ('join_way', models.TextField()),
                ('mtrt_int', models.TextField()),
                ('spcl_cnd', models.TextField()),
                ('join_deny', models.IntegerField(default=0)),
                ('etc_note', models.TextField()),
                ('max_limit', models.IntegerField(blank=True, null=True)),
                ('interest_users', models.ManyToManyField(blank=True, related_name='interest_savings', through='finlife.SavingInterest', to=settings.AUTH_USER_MODEL)),
                ('joined_users', models.ManyToManyField(blank=True, related_name='joined_savings', through='finlife.SavingJoin', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SavingOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intr_rate_type', models.CharField(max_length=100)),
                ('intr_rate_type_nm', models.CharField(max_length=100)),
                ('rsrv_type', models.TextField()),
                ('rsrv_type_nm', models.TextField()),
                ('save_trm', models.IntegerField()),
                ('intr_rate', models.FloatField(null=True)),
                ('intr_rate2', models.FloatField(null=True)),
                ('saving_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finlife.savingproducts')),
            ],
        ),
        migrations.AddField(
            model_name='savingjoin',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finlife.savingproducts'),
        ),
        migrations.AddField(
            model_name='savingjoin',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='savinginterest',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finlife.savingproducts'),
        ),
        migrations.AddField(
            model_name='savinginterest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DepositProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dcls_month', models.TextField()),
                ('fin_co_no', models.TextField()),
                ('kor_co_nm', models.TextField()),
                ('fin_prdt_cd', models.TextField(unique=True)),
                ('fin_prdt_nm', models.TextField()),
                ('join_way', models.TextField()),
                ('mtrt_int', models.TextField()),
                ('spcl_cnd', models.TextField()),
                ('join_deny', models.IntegerField(default=0)),
                ('etc_note', models.TextField()),
                ('max_limit', models.IntegerField(blank=True, null=True)),
                ('interest_users', models.ManyToManyField(blank=True, related_name='interest_deposits', through='finlife.DepositInterest', to=settings.AUTH_USER_MODEL)),
                ('joined_users', models.ManyToManyField(blank=True, related_name='joined_deposits', through='finlife.DepositJoin', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DepositOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intr_rate_type', models.CharField(max_length=100)),
                ('intr_rate_type_nm', models.CharField(max_length=100)),
                ('save_trm', models.IntegerField()),
                ('intr_rate', models.FloatField(null=True)),
                ('intr_rate2', models.FloatField(null=True)),
                ('deposit_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finlife.depositproducts')),
            ],
        ),
        migrations.AddField(
            model_name='depositjoin',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finlife.depositproducts'),
        ),
        migrations.AddField(
            model_name='depositjoin',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='depositinterest',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finlife.depositproducts'),
        ),
        migrations.AddField(
            model_name='depositinterest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='savingjoin',
            unique_together={('user', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='savinginterest',
            unique_together={('user', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='depositjoin',
            unique_together={('user', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='depositinterest',
            unique_together={('user', 'product')},
        ),
    ]
