# Generated by Django 4.2.20 on 2025-05-20 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finlife', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='depositproducts',
            old_name='interest_user',
            new_name='interest_users',
        ),
    ]
